name:                jlc2332-COMSW4995-FinalProj-PalPar
version:             0.1.0.0
github:              "githubuser/jlc2332-COMSW4995-FinalProj-PalPar"
license:             BSD3
author:              "Jesse Lin Chong"
maintainer:          "jlc2332@columbia.edu"
copyright:           "2021 Jesse Lin Chong"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jlc2332-COMSW4995-FinalProj-PalPar#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  jlc2332-COMSW4995-FinalProj-PalPar-exe:
    main:                PalParMain.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jlc2332-COMSW4995-FinalProj-PalPar

tests:
  jlc2332-COMSW4995-FinalProj-PalPar-test:
    main:                PalParSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jlc2332-COMSW4995-FinalProj-PalPar
    - HUnit
